name : First-workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: printing message
        run:  echo "hello sahithi!!!"
      - name: print second message
        run:  echo "bye "
